import React, { useState } from 'react'

const Home = () => {
    const[loading, setloading] = useState(false);
    const[Allposts, setAllposts] = useState(null);

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[32px] text-[#222328]'>
                The community showcase
            </h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
                Browse through a collection of imaginative and visually stunning images
                generated by DALL-E sasdasd
            </p>
        </div>
    </section>
  )
}

export default Home